/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_thesycon_usbio_UsbIo */

#ifndef _Included_de_thesycon_usbio_UsbIo
#define _Included_de_thesycon_usbio_UsbIo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    createDeviceList
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_createDeviceList
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    open
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_open
  (JNIEnv *, jobject, jobject, jint, jint, jstring);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    close
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)V
 */
JNIEXPORT void JNICALL Java_de_thesycon_usbio_UsbIo_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    acquireDevice
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_acquireDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    releaseDevice
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_releaseDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    destroyDeviceList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_thesycon_usbio_UsbIo_destroyDeviceList
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDescriptor
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[IIBBS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDescriptor
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jint, jbyte, jbyte, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setDescriptor
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[IIBBS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setDescriptor
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jint, jbyte, jbyte, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getStringDescriptor
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[IBI)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getStringDescriptor
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyte, jint);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getConfigurationDescriptor
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[IB)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getConfigurationDescriptor
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyte);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDeviceDescriptor
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDeviceDescriptor
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDeviceParameters
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDeviceParameters
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setDeviceParameters
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setDeviceParameters
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDriverInfo
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDriverInfo
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setConfiguration
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setConfiguration
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getConfiguration
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getConfiguration
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getConfigurationInfo
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getConfigurationInfo
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    unconfigureDevice
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_unconfigureDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDeviceInfo
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDeviceInfo
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getInterface
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[BS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getInterface
  (JNIEnv *, jobject, jobject, jbyteArray, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setInterface
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setInterface
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    clearFeature
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;ISS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_clearFeature
  (JNIEnv *, jobject, jobject, jint, jshort, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setFeature
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;ISS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setFeature
  (JNIEnv *, jobject, jobject, jint, jshort, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    cyclePort
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_cyclePort
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    resetDevice
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_resetDevice
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getCurrentFrameNumber
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[I)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getCurrentFrameNumber
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getStatus
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[SIS)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getStatus
  (JNIEnv *, jobject, jobject, jshortArray, jint, jshort);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getDevicePowerState
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[I)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getDevicePowerState
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    setDevicePowerState
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;I)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_setDevicePowerState
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    classOrVendorInRequest
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_classOrVendorInRequest
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    classOrVendorOutRequest
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_classOrVendorOutRequest
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    getBandwidthInfo
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIo_getBandwidthInfo
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    errorText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_thesycon_usbio_UsbIo_errorText
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    isCheckedBuild
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_thesycon_usbio_UsbIo_isCheckedBuild
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    isDemoVersion
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_thesycon_usbio_UsbIo_isDemoVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    isLightVersion
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_thesycon_usbio_UsbIo_isLightVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    isOperatingAtHighSpeed
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_thesycon_usbio_UsbIo_isOperatingAtHighSpeed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIo
 * Method:    isOpen
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_thesycon_usbio_UsbIo_isOpen
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_thesycon_usbio_UsbIoPipe */

#ifndef _Included_de_thesycon_usbio_UsbIoPipe
#define _Included_de_thesycon_usbio_UsbIoPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    bind
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;IBILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_bind
  (JNIEnv *, jobject, jobject, jint, jbyte, jint, jstring);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    unbind
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_unbind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    abortPipe
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_abortPipe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    resetPipe
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_resetPipe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    resetPipeStatistics
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_resetPipeStatistics
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    setupPipeStatistics
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;I)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_setupPipeStatistics
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    queryPipeStatistics
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[BI)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_queryPipeStatistics
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    getPipeParameters
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_getPipeParameters
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    setPipeParameters
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_setPipeParameters
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    readSync
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[II)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_readSync
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jint);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    read
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;Lde/thesycon/usbio/UsbIoBuf;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_read
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    writeSync
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[II)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_writeSync
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jint);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    write
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;Lde/thesycon/usbio/UsbIoBuf;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_write
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    waitForCompletion
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;Lde/thesycon/usbio/UsbIoBuf;I)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_waitForCompletion
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    pipeControlTransferIn
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_pipeControlTransferIn
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     de_thesycon_usbio_UsbIoPipe
 * Method:    pipeControlTransferOut
 * Signature: (Lde/thesycon/usbio/structs/HANDLE;[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_UsbIoPipe_pipeControlTransferOut
  (JNIEnv *, jobject, jobject, jbyteArray, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_thesycon_usbio_PnPNotify */

#ifndef _Included_de_thesycon_usbio_PnPNotify
#define _Included_de_thesycon_usbio_PnPNotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_thesycon_usbio_PnPNotify
 * Method:    disablePnPNotification
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_PnPNotify_disablePnPNotification
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_thesycon_usbio_PnPNotify
 * Method:    enablePnPNotification
 * Signature: (Ljava/lang/String;Lde/thesycon/usbio/PnPNotifyInterface;)I
 */
JNIEXPORT jint JNICALL Java_de_thesycon_usbio_PnPNotify_enablePnPNotification
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
