//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by USBIOAPP.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_USBIOAPP_DIALOG             102
#define IDS_DIALOGPAGE_DEVICE           102
#define IDS_DIALOGPAGE_DESC             103
#define IDS_DIALOGPAGE_CONFIG           104
#define IDS_STRING_INVALID_NUM          105
#define IDS_DIALOGPAGE_INTERFACE        106
#define IDS_DIALOGPAGE_DEVREQ           107
#define IDS_DIALOGPAGE_OTHER            108
#define IDS_DIALOGPAGE_PIPES            109
#define IDS_PDIALOGPAGE_BUFFER          110
#define IDS_PDIALOGPAGE_READTOWIN       111
#define IDS_PDIALOGPAGE_PIPE_PARAMS     112
#define IDS_PDIALOGPAGE_READTOFILE      113
#define IDS_STRING_INVALID_BUFFER       114
#define IDS_DIALOGPAGE_FEATURE          115
#define IDR_MAINFRAME                   128
#define IDD_DIALOGPAGE_DEVICE           129
#define IDD_DIALOGPAGE_DESC             130
#define IDD_OUTPUT_WINDOW               131
#define IDD_DIALOGPAGE_CONFIG           132
#define IDD_PIPE_DIALOG                 134
#define IDD_DIALOGPAGE_INTERFACE        135
#define IDD_DIALOGPAGE_DEVREQ           136
#define IDD_DIALOGPAGE_OTHER            137
#define IDD_DIALOGPAGE_PIPES            138
#define IDD_PDIALOGPAGE_BUFFER          139
#define IDD_PDIALOGPAGE_READTOWIN       140
#define IDD_PDIALOGPAGE_PIPEPARAMS      141
#define IDD_PDIALOGPAGE_READTOFILE      142
#define IDD_PDIALOGPAGE_WRITEFROMFILE   143
#define IDS_PDIALOGPAGE_WRITEFROMFILE   143
#define IDD_DIALOGPAGE_FEATURE          144
#define IDS_PDIALOGPAGE_CONTROL         144
#define IDD_DIALOGPAGE_PIPEREQ          145
#define IDS_BUTTON_OPEN                 145
#define IDS_BUTTON_SCAN                 146
#define IDS_BUTTON_CLOSE                147
#define IDS_GET_DEVICE_PARAMETER        148
#define IDS_SET_DEVICE_PARAMETER        149
#define IDS_BUTTON_ACQUIRE              150
#define IDS_UNCONFIGURE_ON_CLOSE        151
#define IDS_RESET_ON_CLOSE              152
#define IDS_ENABLE_WAKEUP               153
#define IDS_DEVICE_REQUEST_TIMEOUT      154
#define IDS_DEVICE_NUMBER               155
#define IDS_BUTTON_DEVICE_DESC          156
#define IDS_EDIT_CONFIG_DESC            157
#define IDS_BUTTON_CONFIG_DESC          158
#define IDS_EDIT_STRING_DESC            159
#define IDS_EDIT_STRING_DESC_LID        160
#define IDS_BUTTON_STRING_DESC          161
#define IDS_EDIT_CONFIG_INDEX           162
#define IDS_BUTTON_SET_CONFIGURATION    163
#define IDS_BUTTON_GET_CONFIGURATION    164
#define IDS_BUTTON_UNCONFIGURE_DEVICE   165
#define IDS_EDIT_IFNB                   166
#define IDS_EDIT_ASNB                   167
#define IDS_EDIT_MAXTR                  168
#define IDS_CHECK_IF                    169
#define IDS_EDIT_IFNB1                  170
#define IDS_EDIT_ASNB1                  171
#define IDS_BUTTON_SET_INTERFACE        172
#define IDS_BUTTON_GET_INTERFACE        173
#define IDS_BUTTON_GET_PIPE_INFO        174
#define IDS_ENDPOINT_ADDRESS            175
#define IDS_COMBO_ENDPOINTS             175
#define IDS_BUTTON_RELEASE              175
#define IDS_COMBO_PURPOSE               176
#define IDS_BUTTON_OPEN_PIPE            177
#define IDS_COMBO_DIRECTION             178
#define IDS_COMBO_TYPE                  179
#define IDS_COMBO_RECIPIENT             180
#define IDS_EDIT_REQUEST                181
#define IDS_EDIT_VALUE                  182
#define IDS_EDIT_INDEX                  183
#define IDS_CHECK_SHORT_OK              184
#define IDS_EDIT_BUFFER                 185
#define IDS_EDIT_BUFFER_LENGTH          186
#define IDS_BUTTON_SEND_REQUEST         187
#define IDS_COMBO_RECIPIENT4            188
#define IDS_EDIT_FEATURE_SELECTOR       189
#define IDS_EDIT_INDEX4                 190
#define IDS_SET_FEATURE                 191
#define IDS_CLEAR_FEATURE               192
#define IDS_BUTTON_GET_CURRENT_FNB      193
#define IDS_BUTTON_RESET_DEVICE         194
#define IDS_BUTTON_CYCLE_PORT           195
#define IDS_BUTTON_GET_STATUS           196
#define IDS_COMBO_RECIPIENT3            197
#define IDS_EDIT_INDEX3                 198
#define IDS_BUTTON_SET_POWER            199
#define IDS_COMBO_POWER                 200
#define IDS_BUTTON_GET_POWER            201
#define IDS_BUTTON_OUTPUT_WINDOW        202
#define IDS_BUTTON_CLEAR_OUTPUT_WINDOW  203
#define IDS_IDOK                        204
#define IDS_BUTTON_ABORT_PIPE           205
#define IDS_BUTTON_RESET_PIPE           206
#define IDS_BUTTON_GET_PIPE_PARAMS      207
#define IDS_BUTTON_SET_PIPE_PARAMS      208
#define IDS_EDIT_BUF_SIZE               209
#define IDS_EDIT_BUF_COUNT              210
#define IDS_EDIT_MAX_ERRCOUNT           211
#define IDS_EDIT_ISO_PACKET_COUNT       212
#define IDS_PIPE_COMBO_DIRECTION        213
#define IDS_SHORT_TRANSFER_OK           214
#define IDS_PIPE_SETUP                  215
#define IDS_PIPE_EDIT_BUFFER            216
#define IDS_PIPE_EDIT_BUFFER_LENGTH     217
#define IDS_BUTTON_PIPE_SEND_REQUEST    218
#define IDS_EDIT_DST_FILE               219
#define IDS_BUTTON_DST_FILE_BROWSE      220
#define IDS_BUTTON_START_READINGTOFILE  221
#define IDS_BUTTON_STOP_READINGTOFILE   222
#define IDS_CHECK_PRINT_OUT             223
#define IDS_BUTTON_SRC_FILE_BROWSE      224
#define IDC_TAB_MAIN                    1001
#define IDC_BUTTON_OUTPUT_WINDOW        1002
#define IDC_BUTTON_SCAN                 1003
#define IDC_BUTTON_OPEN                 1004
#define IDC_BUTTON_CLEAR_OUTPUT_WINDOW  1004
#define IDC_BUTTON_CLOSE                1005
#define IDC_BUTTON_DEVICE_DESC          1007
#define IDC_BUTTON_CONFIG_DESC          1008
#define IDC_BUTTON_STRING_DESC          1009
#define IDC_EDIT_CONFIG_DESC            1010
#define IDC_EDIT_STRING_DESC            1011
#define IDC_EDIT_OUTPUTWIN              1011
#define IDC_DEVICE_NUMBER               1012
#define IDC_EDIT_BUF_SIZE               1012
#define IDC_EDIT_DST_FILE               1012
#define IDC_EDIT_SAMPLE_RATE            1012
#define IDC_EDIT_STRING_DESC_LID        1012
#define IDC_EDIT_STATS_MEAN_RATE        1012
#define IDC_EDIT_BUF_COUNT              1013
#define IDC_DEVICE_REQUEST_TIMEOUT      1013
#define IDC_EDIT_STATS_BYTES_TRANSFERRED 1013
#define IDC_EDIT_ASNB_0                 1014
#define IDC_EDIT_MAX_ERRCOUNT           1014
#define IDC_EDIT_STATS_REQ_SUCCEEDED    1014
#define IDC_EDIT_MAXTR_0                1015
#define IDC_EDIT_ISO_PACKET_COUNT       1015
#define IDC_EDIT_STATS_REQ_FAILED       1015
#define IDC_CHECK_IF_0                  1016
#define IDC_EDIT_IFNB_0                 1017
#define IDC_EDIT_CONFIG_INDEX           1019
#define IDC_BUTTON_SET_CONFIGURATION    1020
#define IDC_BUTTON_GET_CONFIGURATION    1021
#define IDC_BUTTON_UNCONFIGURE_DEVICE   1022
#define IDC_TAB_PIPE                    1023
#define IDC_EDIT_IFNB                   1024
#define IDC_EDIT_ASNB                   1025
#define IDC_EDIT_MAXTR                  1026
#define IDC_BUTTON_SET_INTERFACE        1027
#define IDC_BUTTON_GET_INTERFACE        1028
#define IDC_COMBO_DIRECTION             1028
#define IDC_COMBO_TYPE                  1029
#define IDC_EDIT_IFNB_1                 1030
#define IDC_COMBO_RECIPIENT             1030
#define IDC_EDIT_ASNB_1                 1031
#define IDC_EDIT_REQUEST                1031
#define IDC_EDIT_MAXTR_1                1032
#define IDC_EDIT_VALUE                  1032
#define IDC_CHECK_IF_1                  1033
#define IDC_BUTTON_RESET_DEVICE         1033
#define IDC_EDIT_IFNB_2                 1034
#define IDC_EDIT_INDEX                  1034
#define IDC_BUTTON_GET_CURRENT_FNB      1034
#define IDC_EDIT_ASNB_2                 1035
#define IDC_BUTTON_GET_PIPE_INFO        1035
#define IDC_EDIT_BUFFER                 1035
#define IDC_EDIT_INDEX3                 1035
#define IDC_EDIT_MAXTR_2                1036
#define IDC_EDIT_BUFFER_LENGTH          1036
#define IDC_CHECK_IF_2                  1037
#define IDC_PIPE_SETUP                  1037
#define IDC_EDIT_IFNB_3                 1038
#define IDC_EDIT_ASNB_3                 1039
#define IDC_BUTTON_START_READINGTOWIN   1039
#define IDC_EDIT_MAXTR_3                1040
#define IDC_BUTTON_STOP_READINGTOFILE   1040
#define IDC_CHECK_IF_3                  1041
#define IDC_CHECK_PRINT_OUT             1041
#define IDC_BUTTON_ABORT_PIPE           1042
#define IDC_BUTTON_RESET_PIPE           1043
#define IDC_CHECK_SHORT_OK              1044
#define IDC_BUTTON_GET_PIPE_PARAMS      1045
#define IDC_BUTTON_START_READINGTOFILE  1045
#define IDC_BUTTON_SET_PIPE_PARAMS      1046
#define IDC_BUTTON_STOP_READINGTOWIN    1046
#define IDC_BUTTON_START_WRITINGFROMFILE 1047
#define IDS_BUTTON_START_WRITINGFROMFILE 1047
#define IDC_BUTTON_STOP_WRITINGFROMFILE 1048
#define IDS_BUTTON_STOP_WRITINGFROMFILE 1048
#define IDC_BUTTON_DST_FILE_BROWSE      1049
#define IDC_BUTTON_SEND_ZERO_PACKET     1049
#define IDS_REWIND                      1049
#define IDC_EDIT_SRC_FILE               1050
#define IDS_EDIT_SRC_FILE               1050
#define IDC_BUTTON_SRC_FILE_BROWSE      1051
#define IDS_BUTTON_SEND_ZERO_PACKET     1051
#define IDS_EDIT_SAMPLE_RATE            1052
#define IDC_BUTTON_SEND_REQUEST         1053
#define IDS_EDIT_SAMPLE_SIZE            1053
#define IDC_BUTTON_GET_STATUS           1054
#define IDS_EDIT_OS_CONFIG_DESC         1054
#define IDC_COMBO_RECIPIENT3            1055
#define IDC_COMBO_RECIPIENT4            1056
#define IDC_EDIT_FEATURE_SELECTOR       1057
#define IDC_EDIT_INDEX4                 1058
#define IDC_SET_FEATURE                 1059
#define IDC_CLEAR_FEATURE               1060
#define IDC_UNCONFIGURE_ON_CLOSE        1060
#define IDC_RESET_ON_CLOSE              1061
#define IDC_GET_DEVICE_PARAMETER        1063
#define IDC_SET_DEVICE_PARAMETERS       1064
#define IDC_PIPE_COMBO_DIRECTION        1065
#define IDC_PIPE_EDIT_BUFFER            1066
#define IDC_PIPE_EDIT_BUFFER_LENGTH     1067
#define IDC_BUTTON_PIPE_SEND_REQUEST    1068
#define IDC_SHORT_TRANSFER_OK           1069
#define IDC_BUTTON_TEST1                1070
#define IDC_BUTTON_TEST2                1071
#define IDC_REWIND                      1072
#define IDC_EDIT_SAMPLE_SIZE            1073
#define IDC_COMBO_POWER                 1074
#define IDC_BUTTON_SET_POWER            1075
#define IDC_BUTTON_GET_POWER            1076
#define IDC_VERSION_INFO                1080
#define IDC_BUTTON_CYCLE_PORT           1081
#define IDC_NB_ISO                      1082
#define IDC_ENABLE_WAKEUP               1083
#define IDC_STATIC_VERSION              1084
#define IDC_STATIC_ABOUT_HL             1085
#define IDC_STATIC_DEV_HL               1086
#define IDC_STATIC_ABOUT_VER            1087
#define IDC_STATIC_ABOUT_COPYRIGHT      1088
#define IDC_STATIC_DEV_NOT_CONFIGURED   1092
#define IDC_BUTTON_DEVICE_QUALIFIER_DESC 1093
#define IDS_BUTTON_DEVICE_QUALIFIER_DESC 1093
#define IDC_BUTTON_OTHER_SPEED_CONFIG_DESC 1094
#define IDS_BUTTON_OTHER_SPEED_CONFIG_DESC 1094
#define IDS_BUTTON_BANDWIDTH            1095
#define IDC_BUTTON_BANDWIDTH            1096
#define IDS_EDIT_ANY_DESC_TYPE          1096
#define IDC_EDIT_ANY_DESC_TYPE          1097
#define IDS_EDIT_ANY_DESC_INDEX         1097
#define IDC_EDIT_ANY_DESC_INDEX         1098
#define IDC_EDIT_ANY_DESC_LENGTH        1099
#define IDS_EDIT_ANY_DESC_LENGTH        1099
#define IDC_BUTTON_ANY_DESC             1100
#define IDS_BUTTON_ANY_DESC             1100
#define IDC_LIST_ENDPOINTS              1101
#define IDS_LIST_ENDPOINTS              1101
#define IDC_BUTTON_OPEN_PIPE_TOWIN      1102
#define IDS_BUTTON_OPEN_PIPE_TOWIN      1102
#define IDC_BUTTON_OPEN_PIPE_TOFILE     1103
#define IDS_BUTTON_OPEN_PIPE_TOFILE     1103
#define IDC_BUTTON_BUFFER_SET_DEFAULTS  1103
#define IDC_BUTTON_OPEN_PIPE_FROMFILE   1104
#define IDS_BUTTON_OPEN_PIPE_FROMFILE   1104
#define IDC_LIST_DEVICES                1104
#define IDS_EDIT_STATS_MEAN_RATE        1105
#define IDC_BUTTON_RESET_PIPE_STATISTICS 1105
#define IDS_EDIT_STATS_BYTES_TRANSFERRED 1106
#define IDC_BUTTON_DOCK_OUTPUT_WINDOW   1106
#define IDS_EDIT_STATS_REQ_SUCCEEDED    1107
#define IDC_DEVICE_INFO                 1107
#define IDS_EDIT_STATS_REQ_FAILED       1108
#define IDC_BUTTON_ACQUIRE              1108
#define IDC_BUTTON_RELEASE              1109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
